# Generated by Django 3.1.5 on 2021-01-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
