# Generated by Django 3.1.5 on 2021-01-07 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklep_sportowy_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartyKlienta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('punkty', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Konta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_adresy', models.ForeignKey(db_column='id_adresy', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.adresy')),
                ('id_karta_klienta', models.ForeignKey(db_column='id_karta_klienta', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.kartyklienta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KontaPracownicze',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('hasło', models.CharField(max_length=255)),
                ('imie', models.CharField(db_column='Imie', max_length=255)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=255)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('email', models.CharField(max_length=30, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=30)),
                ('cena', models.FloatField()),
                ('dla_kogo', models.CharField(max_length=1)),
                ('liczba_dostepnych', models.IntegerField()),
                ('img_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cena_suma', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('data_zamowienia', models.DateField()),
                ('id_adres', models.ForeignKey(db_column='id_adres', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.adresy')),
                ('id_konto', models.ForeignKey(blank=True, db_column='id_konto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.konta')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Znizki',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('czy_procentowa', models.IntegerField()),
                ('wartosc', models.FloatField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reklamacje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_reklamacji', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('powod_reklamacji', models.CharField(max_length=255)),
                ('preferowane_rozwiazanie', models.CharField(choices=[('ZW', 'Zwrot za gotówke'), ('W', 'Wymiana na nowy'), ('N', 'Naprawa')], max_length=30)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.adresy')),
                ('id_podukt', models.ForeignKey(db_column='id_podukt', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.produkty')),
                ('kontaid', models.ForeignKey(db_column='Kontaid', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.konta')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produkty',
            name='id_znizka',
            field=models.ForeignKey(blank=True, db_column='id_znizka', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.znizki'),
        ),
        migrations.CreateModel(
            name='ZamowieniaProdukty',
            fields=[
                ('zamowieniaid', models.OneToOneField(db_column='Zamowieniaid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sklep_sportowy_application.zamowienia')),
                ('licznosc', models.IntegerField()),
                ('produktyid', models.ForeignKey(db_column='Produktyid', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.produkty')),
            ],
            options={
                'managed': True,
                'unique_together': {('zamowieniaid', 'produktyid')},
            },
        ),
    ]
