# Generated by Django 3.1.5 on 2021-01-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_sportowy_application', '0003_auto_20210107_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowieniaprodukty',
            name='zamowieniaid',
            field=models.ForeignKey(db_column='Zamowieniaid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sklep_sportowy_application.zamowienia'),
        ),
    ]
