# Generated by Django 3.1.5 on 2021-01-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_sportowy_application', '0005_auto_20210107_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowieniaprodukty',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zamowieniaprodukty',
            name='zamowieniaid',
            field=models.ForeignKey(db_column='Zamowieniaid', on_delete=django.db.models.deletion.DO_NOTHING, to='sklep_sportowy_application.zamowienia'),
        ),
    ]
