# Generated by Django 3.1.5 on 2021-01-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_sportowy_application', '0006_auto_20210107_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='czy_oplacony',
            field=models.BooleanField(default=False),
        ),
    ]
