# Generated by Django 3.1.5 on 2021-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_sportowy_application', '0007_zamowienia_czy_oplacony'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='czy_dostepny',
            field=models.BooleanField(default=True),
        ),
    ]
